// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPUZv2Z3AiApJw_H_ldD8iRZ8qdq4_Wkw',
    appId: '1:11181735088:web:d6b5589eb69a4779070f75',
    messagingSenderId: '11181735088',
    projectId: 'flowtask-70741',
    authDomain: 'flowtask-70741.firebaseapp.com',
    storageBucket: 'flowtask-70741.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_tjBbDvNsOO5FUKAOh8Ko_8Fc1ukEbGo',
    appId: '1:11181735088:android:b24caa758371f120070f75',
    messagingSenderId: '11181735088',
    projectId: 'flowtask-70741',
    storageBucket: 'flowtask-70741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7M6b_iZUW6lqUOZWf34Ym2JYw3FR6YR4',
    appId: '1:11181735088:ios:58033dc98d1d706b070f75',
    messagingSenderId: '11181735088',
    projectId: 'flowtask-70741',
    storageBucket: 'flowtask-70741.firebasestorage.app',
    iosBundleId: 'com.example.flowtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7M6b_iZUW6lqUOZWf34Ym2JYw3FR6YR4',
    appId: '1:11181735088:ios:58033dc98d1d706b070f75',
    messagingSenderId: '11181735088',
    projectId: 'flowtask-70741',
    storageBucket: 'flowtask-70741.firebasestorage.app',
    iosBundleId: 'com.example.flowtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPUZv2Z3AiApJw_H_ldD8iRZ8qdq4_Wkw',
    appId: '1:11181735088:web:f4df69e8a29075db070f75',
    messagingSenderId: '11181735088',
    projectId: 'flowtask-70741',
    authDomain: 'flowtask-70741.firebaseapp.com',
    storageBucket: 'flowtask-70741.firebasestorage.app',
  );
}
